# Generated by Django 3.1 on 2022-01-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='varation_catagory',
            new_name='varation_category',
        ),
    ]
