# Generated by Django 3.1 on 2022-01-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cartitem_varations'),
        ('store', '0003_auto_20220113_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
