# Generated by Django 3.0.5 on 2022-01-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_varation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='varation',
        ),
    ]
