# Generated by Django 3.0.5 on 2022-01-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('carts', '0003_remove_cartitem_varation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
