# Generated by Django 3.1 on 2022-01-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20220111_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='varations',
        ),
    ]
