# Generated by Django 3.1 on 2022-01-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variation'),
        ('carts', '0006_remove_cartitem_varations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varations',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
